[project]
name = "app"
version = "0.1.0"
description = ""
# readme = "README.md"
requires-python = ">=3.12"

[project.scripts]
app = "app:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
